language: php

php:
  - 8.0.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer validate
  - composer self-update

install:
  - composer update

script:
  - composer test

jobs:
  fast_finish: true
  include:
    - stage: Code Quality
      name: Static analysis
      php: 8.0.3
      install:
        - composer global require --dev phpmetrics/phpmetrics ^2.6
      script:
        - composer global exec -v -- phpmetrics --exclude=Exception src

    - stage: Code Quality
      name: Code Standards
      php: 8.0.3
      install: composer global require --dev friendsofphp/php-cs-fixer ^2.0;
      script:
        - composer global exec -v -- php-cs-fixer  --dry-run -v fix
