language: php
sudo: false

php:
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit;

jobs:
  fast_finish: true
  include:
    - stage: Code Quality
      name: Static analysis
      php: 7.4
      install:
        - composer global require --dev phpmetrics/phpmetrics ^2.6;
      script:
        - ~/.composer/vendor/bin/phpmetrics --exclude=Exception src

    - stage: Code Quality
      name: Code Standards
      php: 7.4
      install: composer global require --dev friendsofphp/php-cs-fixer ^2.0;
      script:
        - ~/.composer/vendor/bin/php-cs-fixer --dry-run -v fix;
